name: Daily Video Scrape
on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3a9c3f75e6cc5a7a323ff0fa27dee8ff2ad659b1
      
      - uses: actions/setup-python@82c7e631bb3c3ad8e1784d0ebf20a0a63ad9dcd0
        with:
          python-version: '3.9'
          cache: 'pip'
          cache-dependency-path: 'scraper/requirements.txt'
      
      - run: pip install -r requirements.txt
        working-directory: scraper
      
      - run: python scraper/scraper.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git add videos.json
            git commit -m "Auto-update [skip ci]"
            git push
          fi
